In [1]:
import os
import json

import pydicom

import pandas as pd

import glob

In [2]:
pwd

'/Users/alexi/Documents/7thYrDocuments/ECIQC/ECIQC'

In [3]:


# os.chdir("..")

In [4]:
### read json file

base_json_dir = "schema"
test_dir = "tests"

useCase_json = "useCase.json"

test_and_json = "test_and.json"
test_clear_json = "test_clear.json"
test_copy_json = "test_copy.json"
test_existappend_json = "test_existappend.json"
test_floatchange_json = "test_floatchange.json"
test_insert_json = "test_insert.json"
test_namechange_json = "test_namechange.json"
test_or_json = "test_or.json"
test_regexprepend_json = "test_regexprepend.json"
test_uintchange_json = "test_uintchange.json"
test_update_json = "test_update.json"

test_pipeline_json = "PipelineCase.json"

test_json_path = os.path.join(base_json_dir, useCase_json)
# with open(test_json_path) as f:
#     test_json = json.load(f)
    
test_json = pd.read_json(test_json_path)

In [5]:
test_json_path = os.path.join(base_json_dir, useCase_json)

In [6]:
print(test_json)

               receiver      destination      quarentine  \
aetitle      TestQCTool  TestDestination  TestQuarentine
port              11112            11113           11114
hostname            NaN        localhost       localhost
(0010,0010)         NaN              NaN             NaN
(0020,0010)         NaN              NaN             NaN
(0010,0040)         NaN              NaN             NaN

                                                      metadata
aetitle                                                    NaN
port                                                       NaN
hostname                                                   NaN
(0010,0010)  {'tagName': 'PatientName', 'vr': 'CS', 'descri...
(0020,0010)  {'tagName': 'PatientAge', 'vr': 'AS', 'operati...
(0010,0040)  {'tagName': 'PatientSex', 'vr': 'CS', 'descrip...

In [7]:
test_dicom_path = "DICOM_Images/1-004.dcm"

ds = pydicom.dcmread(test_dicom_path)

In [8]:
pwd

'/Users/alexi/Documents/7thYrDocuments/ECIQC/ECIQC'

In [9]:
### add JSON file name to DF instead of having seperate dataframes
json_df = pd.DataFrame(columns=["jsonName", "tagName", "IFtagValue", "THENtagOutput", "jsonDIR", "dcmName", "dcmDIR"])

In [10]:
json_df

Empty DataFrame
Columns: [jsonName, tagName, IFtagValue, THENtagOutput, jsonDIR, dcmName, dcmDIR]
Index: []

In [11]:
# json = None
# default_row = {"jsonName": json,"tagName": None, "IFtagValue": None, "THENtagOutput": None}

# default_row = pd.DataFrame(default_row, index=[0])
# json_df = pd.concat([json_df,default_row], ignore_index=True)

In [12]:
json_df

Empty DataFrame
Columns: [jsonName, tagName, IFtagValue, THENtagOutput, jsonDIR, dcmName, dcmDIR]
Index: []

In [13]:
outside_43_80 = [i for i in range(0, 44)] + [i for i in range(80, 100)]
print(outside_43_80)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [14]:
json = useCase_json
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "bob", "THENtagOutput": "Robert"}

row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": None, "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

outside_43_80 = [i for i in range(0, 43)] + [i for i in range(80, 100)]
row = {"jsonName": json, "tagName": "PatientAge", "IFtagValue": [outside_43_80], "THENtagOutput": 56}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)
between_43_80 = range(43, 80)
row = {"jsonName": json, "tagName": "PatientAge", "IFtagValue": [between_43_80], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)
sexes = ["M", "F"]
row = {"jsonName": json, "tagName": "PatientSex", "IFtagValue": [sexes], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [15]:
json = test_and_json
between_10_20 = range(10, 20)
row = {"jsonName": json, "tagName": "BitsAllocated", "IFtagValue": [between_10_20], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [16]:
json= test_clear_json
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "bob", "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [17]:
json = test_copy_json
row = {"jsonName": json, "tagName": "RequestedProcedureDescription", "IFtagValue": None, "THENtagOutput": "bob"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [18]:
json = test_existappend_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "", "THENtagOutput": "John"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [19]:
json = test_floatchange_json
less_than_2500 = range(0, 2500)
row = {"jsonName": json, "tagName": "RealWorldValueIntercept", "IFtagValue": [less_than_2500], "THENtagOutput": 2000.5}

In [20]:
json = test_insert_json
row = {"jsonName": json, "tagName": "HighBit", "IFtagValue": "", "THENtagOutput": 100}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [21]:
json = test_namechange_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "John Doe", "THENtagOutput": "Robert"}

row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [22]:
json = test_or_json
greater_than_10_and_100 = range(10, 1001)
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": [greater_than_10_and_100], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [23]:
json = test_regexprepend_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "John Doe", "THENtagOutput": "Robert"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [24]:
json = test_uintchange_json
row = {"jsonName": json, "tagName": "HighBit", "IFtagValue": 11, "THENtagOutput": 12}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [25]:
json = test_update_json

row = {"jsonName": json, "tagName": "HighBit", "IFtagValue": "", "THENtagOutput": 101}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [26]:
json = test_pipeline_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "John Doe", "THENtagOutput": "Robert"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [27]:
json_df

,jsonName,tagName,IFtagValue,THENtagOutput,jsonDIR,dcmName,dcmDIR
0,useCase.json,PatientName,bob,Robert,NaN,NaN,NaN
1,useCase.json,PatientName,None,None,NaN,NaN,NaN
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,NaN,NaN,NaN
3,useCase.json,PatientAge,"(43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 5...",None,NaN,NaN,NaN
4,useCase.json,PatientSex,"[M, F]",None,NaN,NaN,NaN
5,test_and.json,BitsAllocated,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19)",None,NaN,NaN,NaN
6,test_clear.json,PatientName,bob,None,NaN,NaN,NaN
7,test_copy.json,RequestedProcedureDescription,None,bob,NaN,NaN,NaN
8,test_existappend.json,PatientName,,John,NaN,NaN,NaN
9,test_insert.json,HighBit,,100,NaN,NaN,NaN
10,test_namechange.json,PatientName,John Doe,Robert,NaN,NaN,NaN
11,test_or.json,PatientName,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 2...",None,NaN,NaN,NaN
12,test_regexprepend.json,PatientName,John Doe,Robert,NaN,NaN,NaN
13,test_uintchange.json,HighBit,11,12,NaN,NaN,NaN
14,test_update.json,HighBit,,101,NaN,NaN,NaN
15,PipelineCase.json,PatientName,John Doe,Robert,NaN,NaN,NaN

In [28]:
for idx, row in json_df.iterrows():
    print(row["jsonName"])

    if row["jsonName"] == useCase_json:
        row["jsonDIR"] = base_json_dir

    else:
        row["jsonDIR"] = base_json_dir,test_dir

useCase.json
useCase.json
useCase.json
useCase.json
useCase.json
test_and.json
test_clear.json
test_copy.json
test_existappend.json
test_insert.json
test_namechange.json
test_or.json
test_regexprepend.json
test_uintchange.json
test_update.json
PipelineCase.json

In [29]:
json_df

,jsonName,tagName,IFtagValue,THENtagOutput,jsonDIR,dcmName,dcmDIR
0,useCase.json,PatientName,bob,Robert,schema,NaN,NaN
1,useCase.json,PatientName,None,None,schema,NaN,NaN
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,schema,NaN,NaN
3,useCase.json,PatientAge,"(43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 5...",None,schema,NaN,NaN
4,useCase.json,PatientSex,"[M, F]",None,schema,NaN,NaN
5,test_and.json,BitsAllocated,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19)",None,"(schema, tests)",NaN,NaN
6,test_clear.json,PatientName,bob,None,"(schema, tests)",NaN,NaN
7,test_copy.json,RequestedProcedureDescription,None,bob,"(schema, tests)",NaN,NaN
8,test_existappend.json,PatientName,,John,"(schema, tests)",NaN,NaN
9,test_insert.json,HighBit,,100,"(schema, tests)",NaN,NaN
10,test_namechange.json,PatientName,John Doe,Robert,"(schema, tests)",NaN,NaN
11,test_or.json,PatientName,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 2...",None,"(schema, tests)",NaN,NaN
12,test_regexprepend.json,PatientName,John Doe,Robert,"(schema, tests)",NaN,NaN
13,test_uintchange.json,HighBit,11,12,"(schema, tests)",NaN,NaN
14,test_update.json,HighBit,,101,"(schema, tests)",NaN,NaN
15,PipelineCase.json,PatientName,John Doe,Robert,"(schema, tests)",NaN,NaN

In [30]:
json_df.to_json("expected_test_results.json", orient="records")

In [31]:
json_df = pd.read_json("expected_test_results.json", orient="records")

In [32]:
json_df

,jsonName,tagName,IFtagValue,THENtagOutput,jsonDIR,dcmName,dcmDIR
0,useCase.json,PatientName,bob,Robert,schema,NaN,NaN
1,useCase.json,PatientName,None,None,schema,NaN,NaN
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,schema,NaN,NaN
3,useCase.json,PatientAge,"{'start': 43, 'step': 1, 'stop': 80}",None,schema,NaN,NaN
4,useCase.json,PatientSex,"[M, F]",None,schema,NaN,NaN
5,test_and.json,BitsAllocated,"{'start': 10, 'step': 1, 'stop': 20}",None,"[schema, tests]",NaN,NaN
6,test_clear.json,PatientName,bob,None,"[schema, tests]",NaN,NaN
7,test_copy.json,RequestedProcedureDescription,None,bob,"[schema, tests]",NaN,NaN
8,test_existappend.json,PatientName,,John,"[schema, tests]",NaN,NaN
9,test_insert.json,HighBit,,100,"[schema, tests]",NaN,NaN
10,test_namechange.json,PatientName,John Doe,Robert,"[schema, tests]",NaN,NaN
11,test_or.json,PatientName,"{'start': 10, 'step': 1, 'stop': 1001}",None,"[schema, tests]",NaN,NaN
12,test_regexprepend.json,PatientName,John Doe,Robert,"[schema, tests]",NaN,NaN
13,test_uintchange.json,HighBit,11,12,"[schema, tests]",NaN,NaN
14,test_update.json,HighBit,,101,"[schema, tests]",NaN,NaN
15,PipelineCase.json,PatientName,John Doe,Robert,"[schema, tests]",NaN,NaN

In [33]:
### loop over folder of dicom images

dcm_dir = "DICOM_images"

complete_json_df = pd.DataFrame()

for file in os.listdir(dcm_dir):
    if file.endswith(".dcm"):
        print(file)
        json_append = json_df.copy()

        json_append["dcmName"] = file
        json_append["dcmDIR"] = dcm_dir

        complete_json_df = pd.concat([complete_json_df,json_append], ignore_index=True)

1-006.dcm
1-004.dcm
1-005.dcm
test2.dcm
1-1copy.dcm
1-003.dcm
testtext.dcm
1-01.dcm

In [34]:
complete_json_df

,jsonName,tagName,IFtagValue,THENtagOutput,jsonDIR,dcmName,dcmDIR
0,useCase.json,PatientName,bob,Robert,schema,1-006.dcm,DICOM_images
1,useCase.json,PatientName,None,None,schema,1-006.dcm,DICOM_images
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,schema,1-006.dcm,DICOM_images
3,useCase.json,PatientAge,"{'start': 43, 'step': 1, 'stop': 80}",None,schema,1-006.dcm,DICOM_images
4,useCase.json,PatientSex,"[M, F]",None,schema,1-006.dcm,DICOM_images
...,...,...,...,...,...,...,...
123,test_or.json,PatientName,"{'start': 10, 'step': 1, 'stop': 1001}",None,"[schema, tests]",1-01.dcm,DICOM_images
124,test_regexprepend.json,PatientName,John Doe,Robert,"[schema, tests]",1-01.dcm,DICOM_images
125,test_uintchange.json,HighBit,11,12,"[schema, tests]",1-01.dcm,DICOM_images
126,test_update.json,HighBit,,101,"[schema, tests]",1-01.dcm,DICOM_images
127,PipelineCase.json,PatientName,John Doe,Robert,"[schema, tests]",1-01.dcm,DICOM_images

In [35]:

output_name = "complete_expected_output.json"

output_name = os.path.join(base_json_dir, test_dir ,output_name)

complete_json_df.to_json(output_name, orient="records")

In [36]:
print(output_name)

schema/tests/complete_expected_output.json

In [37]:
!ls

CLI.log                    file_name_list.json
CMakeLists.txt             libs
DF_from_JSON.ipynb         pipelinetest_main.py
DICOM_Images               result
LICENSE                    result_quarantine
README.md                  schema
build                      scripts
codecov.yml                src
docs                       test.dcm
exe                        tests
expected_test_results.json venv

In [38]:
os.path.join("DICOM_Images"," ")

'DICOM_Images/ '

In [42]:
pwd

'/Users/alexi/Documents/7thYrDocuments/ECIQC/ECIQC'

In [43]:
path = "./result/1.3.6.1.4.1.14519.5.2.1.8162.7003.232425522272405527521317182328.dcm"
ds = pydicom.dcmread(path, force=True)
tagName = "PatientName"

In [44]:
realTHENtagOutput = ds.data_element(tagName).value

Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 208
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: CT Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.6.1.4.1.14519.5.2.1.8162.7003.232425522272405527521317182328
(0002, 0010) Transfer Syntax UID                 UI: Implicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.2.826.0.1.3680043.9.3811.2.0.2
(0002, 0013) Implementation Version Name         SH: 'PYNETDICOM_202'
-------------------------------------------------
(0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
(0008, 0008) Image Type                          CS: ['ORIGINAL', 'PRIMARY', 'AXIAL']
(0008, 0012) Instance Creation Date              DA: '19920126'
(0008, 0013) Instance Creation Time              TM: '160830'
(0008, 0016) SOP Class UID                       UI: CT Image Storage
(0008, 0018) SOP Instance UID                    UI: 1.3.6.1.4.1.14519.5.2.1.8162.7003.232425522272405527521317182328
(0008, 0020) Study Date                          DA: '19920126'
(0008, 0021) Series Date                         DA: '19920126'
(0008, 0022) Acquisition Date                    DA: '19920126'
(0008, 0023) Content Date                        DA: '19920126'
(0008, 0030) Study Time                          TM: '160650.00'
(0008, 0031) Series Time                         TM: '160746'
(0008, 0032) Acquisition Time                    TM: '160828'
(0008, 0033) Content Time                        TM: '160830'
(0008, 0050) Accession Number                    SH: '6206217557044190'
(0008, 0060) Modality                            CS: 'CT'
(0008, 0070) Manufacturer                        LO: 'GE MEDICAL SYSTEMS'
(0008, 0090) Referring Physician's Name          PN: ''
(0008, 1010) Station Name                        SH: 'vumcct'
(0008, 1030) Study Description                   LO: 'BREAST PRONE'
(0008, 103e) Series Description                  LO: 'CTAC'
(0008, 1090) Manufacturer's Model Name           LO: 'Discovery STE'
(0010, 0010) Patient's Name                      PN: 'QIN-BREAST-01-0003'
(0010, 0020) Patient ID                          LO: 'QIN-BREAST-01-0003'
(0010, 0030) Patient's Birth Date                DA: ''
(0010, 0040) Patient's Sex                       CS: ''
(0010, 1010) Patient's Age                       AS: '039Y'
(0010, 1020) Patient's Size                      DS: '1.7'
(0010, 1030) Patient's Weight                    DS: '105.0'
(0012, 0062) Patient Identity Removed            CS: 'YES'
(0012, 0063) De-identification Method            LO: 'DCM:113100/113105/113107/113108/113109/113111'
(0013, 0010) Private Creator                     LO: 'CTP'
(0013, 1010) Private tag data                    UN: b'QIN-BREAST'
(0013, 1013) Private tag data                    UN: b'81627003'
(0018, 0015) Body Part Examined                  CS: 'BREAST'
(0018, 0022) Scan Options                        CS: 'HELICAL MODE'
(0018, 0050) Slice Thickness                     DS: '3.75'
(0018, 0060) KVP                                 DS: '120.0'
(0018, 0090) Data Collection Diameter            DS: '500.0'
(0018, 1020) Software Versions                   LO: 'dm09_hl2sp1.23'
(0018, 1030) Protocol Name                       LO: '7.3 PRONE BREAST'
(0018, 1100) Reconstruction Diameter             DS: '700.0'
(0018, 1110) Distance Source to Detector         DS: '949.075012'
(0018, 1111) Distance Source to Patient          DS: '541.0'
(0018, 1120) Gantry/Detector Tilt                DS: '0.0'
(0018, 1130) Table Height                        DS: '140.5'
(0018, 1140) Rotation Direction                  CS: 'CW'
(0018, 1150) Exposure Time                       IS: '873'
(0018, 1151) X-Ray Tube Current                  IS: '121'
(0018, 1152) Exposure                            IS: '21'
(0018, 1160) Filter Type                         SH: 'BODY FILTER'
(0018, 1170) Generator Power                     IS: '14400'
(0018, 1190) Focal Spot(s)                       DS: '0.7'
(0018, 1210) Convolution Kernel                  SH: 'STANDARD'
(0018, 5100) Patient Position                    CS: 'HFP'
(0020, 000d) Study Instance UID                  UI: 1.3.6.1.4.1.14519.5.2.1.8162.7003.158106765581030824023052454676
(0020, 000e) Series Instance UID                 UI: 1.3.6.1.4.1.14519.5.2.1.8162.7003.130669841673086595000374519437
(0020, 0010) Study ID                            SH: ''
(0020, 0011) Series Number                       IS: '2'
(0020, 0012) Acquisition Number                  IS: '1'
(0020, 0013) Instance Number                     IS: '1'
(0020, 0032) Image Position (Patient)            DS: [350, 350, -39.5]
(0020, 0037) Image Orientation (Patient)         DS: [-1, 0, 0, 0, -1, 0]
(0020, 0052) Frame of Reference UID              UI: 1.3.6.1.4.1.14519.5.2.1.8162.7003.399318494684703609897398021250
(0020, 1040) Position Reference Indicator        LO: 'V'
(0020, 1041) Slice Location                      DS: '-39.5'
(0028, 0002) Samples per Pixel                   US: 1
(0028, 0004) Photometric Interpretation          CS: 'MONOCHROME2'
(0028, 0010) Rows                                US: 512
(0028, 0011) Columns                             US: 512
(0028, 0030) Pixel Spacing                       DS: [1.367188, 1.367188]
(0028, 0100) Bits Allocated                      US: 16
(0028, 0101) Bits Stored                         US: 16
(0028, 0102) High Bit                            US: 15
(0028, 0103) Pixel Representation                US: 1
(0028, 0106) Smallest Image Pixel Value          SS: -2000
(0028, 0107) Largest Image Pixel Value           SS: 2526
(0028, 0120) Pixel Padding Value                 SS: -2000
(0028, 0303) Longitudinal Temporal Information M CS: 'MODIFIED'
(0028, 1050) Window Center                       DS: '40.0'
(0028, 1051) Window Width                        DS: '400.0'
(0028, 1052) Rescale Intercept                   DS: '-1024.0'
(0028, 1053) Rescale Slope                       DS: '1.0'
(7fe0, 0010) Pixel Data                          OW: Array of 524288 elements