In [3]:
import os
import json

import pydicom

import pandas as pd

import addict

In [1]:
import torch

In [2]:
print(torch.__version__)

1.13.1

In [32]:
### read json file

base_json_dir = "schema"
test_dir = "tests"

useCase_json = "useCase.json"

test_and_json = "test_and.json"
test_clear_json = "test_clear.json"
test_copy_json = "test_copy.json"
test_existappend_json = "test_existappend.json"
test_floatchange_json = "test_floatchange.json"
test_insert_json = "test_insert.json"
test_namechange_json = "test_namechange.json"
test_or_json = "test_or.json"
test_regexprepend_json = "test_regexprepend.json"
test_uintchange_json = "test_uintchange.json"
test_update_json = "test_update.json"

test_json_path = os.path.join(useCase_json)
# with open(test_json_path) as f:
#     test_json = json.load(f)
    
test_json = pd.read_json(test_json_path)

In [33]:
test_json_path = os.path.join(base_json_dir, useCase_json)

In [34]:
print(test_json)

               receiver      destination      quarentine  \
aetitle      TestQCTool  TestDestination  TestQuarentine
port              11112            11113           11114
hostname            NaN        localhost       localhost
(0010,0010)         NaN              NaN             NaN
(0020,0010)         NaN              NaN             NaN
(0010,0040)         NaN              NaN             NaN

                                                      metadata
aetitle                                                    NaN
port                                                       NaN
hostname                                                   NaN
(0010,0010)  {'tagName': 'PatientName', 'vr': 'CS', 'descri...
(0020,0010)  {'tagName': 'PatientAge', 'vr': 'AS', 'operati...
(0010,0040)  {'tagName': 'PatientSex', 'vr': 'CS', 'descrip...

In [35]:
test_dicom_path = "DICOM_Images/1-004.dcm"

ds = pydicom.dcmread(test_dicom_path)

FileNotFoundError: [Errno 2] No such file or directory: 'DICOM_Images/1-004.dcm'

In [36]:
### add JSON file name to DF instead of having seperate dataframes
json_df = pd.DataFrame(columns=["jsonName", "tagName", "IFtagValue", "THENtagOutput", "dir"])

In [37]:
json_df

Empty DataFrame
Columns: [jsonName, tagName, IFtagValue, THENtagOutput, dir]
Index: []

In [38]:
# json = None
# default_row = {"jsonName": json,"tagName": None, "IFtagValue": None, "THENtagOutput": None}

# default_row = pd.DataFrame(default_row, index=[0])
# json_df = pd.concat([json_df,default_row], ignore_index=True)

In [39]:
json_df

Empty DataFrame
Columns: [jsonName, tagName, IFtagValue, THENtagOutput, dir]
Index: []

In [40]:
outside_43_80 = [i for i in range(0, 44)] + [i for i in range(80, 100)]
print(outside_43_80)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [41]:
json = useCase_json
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "bob", "THENtagOutput": "Robert"}

row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": None, "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

outside_43_80 = [i for i in range(0, 43)] + [i for i in range(80, 100)]
row = {"jsonName": json, "tagName": "PatientAge", "IFtagValue": [outside_43_80], "THENtagOutput": 56}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)
between_43_80 = range(43, 80)
row = {"jsonName": json, "tagName": "PatientAge", "IFtagValue": [between_43_80], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)
sexes = ["M", "F"]
row = {"jsonName": json, "tagName": "PatientSex", "IFtagValue": [sexes], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [42]:
json = test_and_json
between_10_20 = range(10, 20)
row = {"jsonName": json, "tagName": "BitsAllocated", "IFtagValue": [between_10_20], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [43]:
json= test_clear_json
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "bob", "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [44]:
json = test_copy_json
row = {"jsonName": json, "tagName": "RequestedProcedureDescription", "IFtagValue": None, "THENtagOutput": "bob"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [45]:
json = test_existappend_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "", "THENtagOutput": "John"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [46]:
json = test_floatchange_json
less_than_2500 = range(0, 2500)
row = {"jsonName": json, "tagName": "RealWorldValueIntercept", "IFtagValue": [less_than_2500], "THENtagOutput": 2000.5}

In [47]:
json = test_insert_json
row = {"jsonName": json, "tagName": "HighBit", "IFtagValue": "", "THENtagOutput": 100}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [48]:
json = test_namechange_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "John Doe", "THENtagOutput": "Robert"}

row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [49]:
json = test_or_json
greater_than_10_and_100 = range(10, 1001)
row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": [greater_than_10_and_100], "THENtagOutput": None}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [50]:
json = test_regexprepend_json

row = {"jsonName": json, "tagName": "PatientName", "IFtagValue": "John Doe", "THENtagOutput": "Robert"}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [51]:
json = test_uintchange_json
row = {"jsonName": json, "tagName": "HighBit", "IFtagValue": 11, "THENtagOutput": 12}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [52]:
json = test_update_json

row = {"jsonName": json, "tagName": "HighBit", "IFtagValue": "", "THENtagOutput": 101}
row = pd.DataFrame(row, index=[0])
json_df = pd.concat([json_df,row], ignore_index=True)

In [53]:
json_df

,jsonName,tagName,IFtagValue,THENtagOutput,dir
0,useCase.json,PatientName,bob,Robert,NaN
1,useCase.json,PatientName,None,None,NaN
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,NaN
3,useCase.json,PatientAge,"(43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 5...",None,NaN
4,useCase.json,PatientSex,"[M, F]",None,NaN
5,test_and.json,BitsAllocated,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19)",None,NaN
6,test_clear.json,PatientName,bob,None,NaN
7,test_copy.json,RequestedProcedureDescription,None,bob,NaN
8,test_existappend.json,PatientName,,John,NaN
9,test_insert.json,HighBit,,100,NaN
10,test_namechange.json,PatientName,John Doe,Robert,NaN
11,test_or.json,PatientName,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 2...",None,NaN
12,test_regexprepend.json,PatientName,John Doe,Robert,NaN
13,test_uintchange.json,HighBit,11,12,NaN
14,test_update.json,HighBit,,101,NaN

In [54]:
for idx, row in json_df.iterrows():
    print(row["jsonName"])

    if row["jsonName"] == useCase_json:
        row["dir"] = base_json_dir

    else:
        row["dir"] = base_json_dir,test_dir

useCase.json
useCase.json
useCase.json
useCase.json
useCase.json
test_and.json
test_clear.json
test_copy.json
test_existappend.json
test_insert.json
test_namechange.json
test_or.json
test_regexprepend.json
test_uintchange.json
test_update.json

In [55]:
json_df

,jsonName,tagName,IFtagValue,THENtagOutput,dir
0,useCase.json,PatientName,bob,Robert,schema
1,useCase.json,PatientName,None,None,schema
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,schema
3,useCase.json,PatientAge,"(43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 5...",None,schema
4,useCase.json,PatientSex,"[M, F]",None,schema
5,test_and.json,BitsAllocated,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19)",None,"(schema, tests)"
6,test_clear.json,PatientName,bob,None,"(schema, tests)"
7,test_copy.json,RequestedProcedureDescription,None,bob,"(schema, tests)"
8,test_existappend.json,PatientName,,John,"(schema, tests)"
9,test_insert.json,HighBit,,100,"(schema, tests)"
10,test_namechange.json,PatientName,John Doe,Robert,"(schema, tests)"
11,test_or.json,PatientName,"(10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 2...",None,"(schema, tests)"
12,test_regexprepend.json,PatientName,John Doe,Robert,"(schema, tests)"
13,test_uintchange.json,HighBit,11,12,"(schema, tests)"
14,test_update.json,HighBit,,101,"(schema, tests)"

In [59]:
json_df.to_json("expected_test_results.json", orient="records")

In [60]:
json_df = pd.read_json("expected_test_results.json", orient="records")

In [61]:
json_df

,jsonName,tagName,IFtagValue,THENtagOutput,dir
0,useCase.json,PatientName,bob,Robert,schema
1,useCase.json,PatientName,None,None,schema
2,useCase.json,PatientAge,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",56,schema
3,useCase.json,PatientAge,"{'start': 43, 'step': 1, 'stop': 80}",None,schema
4,useCase.json,PatientSex,"[M, F]",None,schema
5,test_and.json,BitsAllocated,"{'start': 10, 'step': 1, 'stop': 20}",None,"[schema, tests]"
6,test_clear.json,PatientName,bob,None,"[schema, tests]"
7,test_copy.json,RequestedProcedureDescription,None,bob,"[schema, tests]"
8,test_existappend.json,PatientName,,John,"[schema, tests]"
9,test_insert.json,HighBit,,100,"[schema, tests]"
10,test_namechange.json,PatientName,John Doe,Robert,"[schema, tests]"
11,test_or.json,PatientName,"{'start': 10, 'step': 1, 'stop': 1001}",None,"[schema, tests]"
12,test_regexprepend.json,PatientName,John Doe,Robert,"[schema, tests]"
13,test_uintchange.json,HighBit,11,12,"[schema, tests]"
14,test_update.json,HighBit,,101,"[schema, tests]"